<header>
	<style>
		.content {
			margin: auto;
			width: 50%;
		}

		hr {
			margin-top: 40px;
		}

		li {
			font-family: sans-serif;
			font-size: 16px;
		}
	</style>
</header>

<body>

	<div class="post-body">
		<h1>Welcome to Ocean!</h1>
		<p>Welcome to Ocean, a free, anonymous, user-driven messaging experience!</p>
		<ul>
			<li><a id="nav-login" href="login.php">Login</a></li>
			<li><a id="nav-create-account" href="create_account.php">Sign Up</a></li>
			<li><a id="nav-learn-more" href="learn_more.php">Learn More</a></li>
		</ul>
	</div>

<hr>

</body>

