<header>
	<div id="ocean-logo">
		<object id="ocean-logo" type="image/svg+xml" data="images/richie_logo1.svg">
			<img id="ocean-logo-fallback" src="images/richie_logo1.png" alt="Ocean Logo">
		</object>
	</div> <!-- ocean-logo -->
	<nav>
		<ul>
			<li><a id="nav-login" href="login.php">Login</a></li>
			<li><a id="nav-create-account" href="create_account.php">Sign Up</a></li>
			<li><a id="nav-learn-more" href="learn_more.php">Learn More</a></li>
		</ul>
	</nav>
</header>

<body>
<div class="content">
		<h1>Welcome to Ocean!</h1>
		<p>Welcome to Ocean, a free, anonymous, user-driven messaging and chat experience.</p>
	</div>  <!-- content -->
</body>

