<div id="subnav-oceans-submenu" class="submenu">
	<ul id="subnav-oceans-ul">
		<li><a id="oceans-submenu-browse" class="oceans-submenu-selectable" role="button">[Browse]</a></li>
		<li><a id="oceans-submenu-viewer" class="oceans-submenu-selectable" role="button">[Viewer]</a></li>
		<li><a id="oceans-submenu-new" class="oceans-submenu-selectable" role="button">[Create New]</a></li>
		<li><a id="oceans-submenu-saved" class="oceans-submenu-selectable" role="button">[Saved Messages]</a></li>
		<li><a id="oceans-submenu-ocean-Open&#32;Waters" class="oceans-submenu-ocean" role="button">Open Waters</a></li>
	</ul>
</div>